name: app_containers

services:

  flask:
    image: jupitercommits/app-cicd-prototype:v1.3
    container_name: flask
    ports:
     - 8081:8080

  nginx:
    image: nginx:1.28.0-alpine-slim
    container_name: nginx
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./reverse_proxy/self_signed:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443

  nginx-prometheus:
    image: nginx/nginx-prometheus-exporter:1.4
    container_name: prometheus_exporter
    ports:
      - 9113:9113
    environment:
      - SCRAPE_URI=https://nginx/metrics
      - NGINX_RETRIES=10
      - TELEMETRY_PATH=/prometheus
    command:
      - -nginx.scrape-uri=https://nginx/metrics

  prometheus:
    image: prom/prometheus:v3.3.1
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - host.docker.internal:host-gateway

  grafana:
    image: grafana/grafana:12.0.0-ubuntu
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana-storage:/var/lib/grafana

  cadvisor:
    image: bitnami/cadvisor:0.52.1
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
