global:
  scrape_interval: 15s
  evaluation_interval: 15s


rule_files:

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: docker
    static_configs:
      - targets: ["host.docker.internal:9323"]

  - job_name: nginx
    metrics_path: /prometheus
    static_configs:
      - targets:
          - prometheus_exporter:9113